on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_native_artifact:
    name: "Build native artifact using GraalVM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: "latest"
          java-version: "17"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native artifact
        run: |
          ./mvnw package -Dmaven.test.skip=true -Pnative

      - name: Upload native_artifact
        uses: actions/upload-artifact@v3
        with:
          name: native_artifact
          path: target/*-runner

      - name: Upload native-micro Dockerfile
        uses: actions/upload-artifact@v3
        with:
          name: micro_dockerfile
          path: src/main/docker/Dockerfile.native-micro

  build_and_push_docker_image:
    name: Build and push docker image to Github Container Registry
    needs: build_native_artifact
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: "Download native artifact"
        uses: actions/download-artifact@v3
        with:
          name: native_artifact

      - name: "Download micro Dockerfile"
        uses: actions/download-artifact@v3
        with:
          name: micro_dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
